# Generated by Django 4.2.13 on 2024-07-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='評価'),
        ),
    ]
