# Generated by Django 4.2.13 on 2024-07-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='prefecture',
            field=models.CharField(blank=True, max_length=5, verbose_name='都道府県'),
        ),
    ]
